@startuml
title Видеохостинг - Use Case диаграмма
' Расположение акторов и use case
skinparam ranksep 100
skinparam nodesep 100
left to right direction
' Акторы
actor "Гость" as Guest
actor "Владелец видео" as Author
actor " Зритель" as Viewer
' Владелец видео является специализацией Зрителя (имеет все его возможности + дополнительные)
Viewer <|-- Author
' Варианты использования (Use cases)
rectangle "Видеохостинг" {
    ' Варианты использования незарегистрированного пользователя (гость)
    package "Управление видео гостем" {
        usecase "Найти видео на платформе" as UC1.1.1
        usecase "Просмотреть видео" as UC1.1.2
        usecase "Зарегистрировать аккаунт" as UC1.1.3              
    }
    ' Варианты использования общие для зарегистрированных пользователей (владелец видео, зритель)
    package "Управление учетной записью (аккаунтом)" {
        usecase "Войти в личный кабинет" as UC1.1.4
        usecase "Выйти из личного кабинета" as UC1.1.5
    }
    ' Варианты использования зарегистрированного пользователя (владелец видео)
    package "Управление видео владельцем видео" {
        usecase "Загрузить видео" as UC2.1.1
        usecase "Добавить название к видео" as UC2.1.2
        usecase "Добавить описание к видео" as UC2.1.3
        usecase "Удалить видео" as UC2.1.4
        usecase "Редактировать видео" as UC2.1.5
    }
    package "Анализ и статистика" {
        usecase "Просмотреть статистику по видео" as UC2.2.1  
    }
    ' Варианты использования зарегистрированного пользователя (зритель)
    package "Управление видео зрителем" {
        usecase "Добавить лайк к видео" as UC3.1.1
        usecase "Отозвать лайк к видео" as UC3.1.2
        usecase "Добавить комментарий к видео" as UC3.1.3
        usecase "Удалить комментарий к видео" as UC3.1.4 
    }
}
' Отношения незарегистрированного пользователя (гость)
Guest --> UC1.1.1
Guest --> UC1.1.2
Guest --> UC1.1.3
' Отношения Общие для зарегистрированных пользователей (владелец видео, зритель)
Viewer --> UC1.1.4
Viewer --> UC1.1.5
' Отношения зарегистрированного пользователя (владелец видео)
Author --> UC2.1.1
Author --> UC2.1.2
Author --> UC2.1.3
Author --> UC2.1.4
Author --> UC2.1.5
Author --> UC2.2.1
' Включения зарегистрированного пользователя (владелец видео)
UC2.1.1 .> UC2.1.2 : <<include>>
UC2.1.1 .> UC2.1.3 : <<include>>
' Расширения зарегистрированного пользователя (владелец видео)
UC2.1.5 .> UC2.1.2 : <<extend>>
UC2.1.5 .> UC2.1.3 : <<extend>>
' Отношения зарегистрированного пользователя (зритель)
Viewer --> UC1.1.1
Viewer --> UC1.1.2
Viewer --> UC3.1.1
Viewer --> UC3.1.2
Viewer --> UC3.1.3
Viewer --> UC3.1.4
@enduml